# Generation of Kubernetes YAML is still under development!
#
# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-3.2.3
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2021-11-27T00:53:29Z"
  labels:
    app: eleventy-fass-ondemand
  name: eleventy-fass-ondemand
spec:
  containers:
  - command:
    - ./faas-content-proxy
    env:
    - name: PATH
      value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    - name: TERM
      value: xterm
    - name: container
      value: oci
    image: quay.io/jamstacknative/faas-content-proxy:latest
    name: greatrhodes
    ports:
    - containerPort: 8090
      hostPort: 8090
      protocol: TCP
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_AUDIT_WRITE
      privileged: false
      readOnlyRootFilesystem: false
      seLinuxOptions: {}
    tty: true
    workingDir: /app
  - args:
    - index.handler
    command:
    - /lambda-entrypoint.sh
    env:
    - name: PATH
      value: /var/lang/bin:/usr/local/bin:/usr/bin/:/bin:/opt/bin
    - name: TERM
      value: xterm
    - name: container
      value: podman
    - name: LD_LIBRARY_PATH
      value: /var/lang/lib:/lib64:/usr/lib64:/var/runtime:/var/runtime/lib:/var/task:/var/task/lib:/opt/lib
    - name: LAMBDA_TASK_ROOT
      value: /var/task
    - name: LAMBDA_RUNTIME_DIR
      value: /var/runtime
    - name: LANG
      value: en_US.UTF-8
    - name: TZ
      value: :/etc/localtime
    - name: S3SECRET
      value: XXXX
    - name: S3BUCKETNAME
      value: core-output-files
    - name: S3ENDPOINT
      value: https://s3.eu-de.cloud-object-storage.appdomain.cloud
    - name: S3ACCESSKEY
      value: XXXX
    image: quay.io/jamstacknative/eleventy-serverless-docker:latest
    name: heuristiceuler
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_AUDIT_WRITE
      privileged: false
      readOnlyRootFilesystem: false
      seLinuxOptions: {}
    tty: true
    workingDir: /var/task
  dnsConfig: {}
  restartPolicy: Never
status: {}
